// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Personal.Dashboard.Core.Common.Storage;

#nullable disable

namespace Personal.Dashboard.Migrations.Host.Migrations
{
    [DbContext(typeof(PersonalDashboardContext))]
    [Migration("20260311112946_AddIsFavoriteToLeague")]
    partial class AddIsFavoriteToLeague
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueAlias", b =>
                {
                    b.Property<string>("AliasSource")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.HasKey("AliasSource", "Alias", "LeagueId");

                    b.HasIndex("LeagueId");

                    b.ToTable("FootballLeagueAlias");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRefreshed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FootballLeagueEntity");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueAlias", b =>
                {
                    b.HasOne("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", "League")
                        .WithMany("Aliases")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
