// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Personal.Dashboard.Core.Common.Storage;

#nullable disable

namespace Personal.Dashboard.Migrations.Host.Migrations
{
    [DbContext(typeof(PersonalDashboardContext))]
    [Migration("20260313133930_AddFootballLeagueSeasons")]
    partial class AddFootballLeagueSeasons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballClubEntityFootballLeagueEntity", b =>
                {
                    b.Property<Guid>("ClubsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaguesId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubsId", "LeaguesId");

                    b.HasIndex("LeaguesId");

                    b.ToTable("FootballLeagueClub", (string)null);
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Clubs.Entities.FootballClubAlias", b =>
                {
                    b.Property<string>("AliasSource")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.HasKey("AliasSource", "Alias", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("FootballClubAlias");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Clubs.Entities.FootballClubEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRefreshed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FootballClubEntity");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueAlias", b =>
                {
                    b.Property<string>("AliasSource")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.HasKey("AliasSource", "Alias", "LeagueId");

                    b.HasIndex("LeagueId");

                    b.ToTable("FootballLeagueAlias");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRefreshed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FootballLeagueEntity");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueSeason", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.HasKey("LeagueId", "Year");

                    b.ToTable("FootballLeagueSeason");
                });

            modelBuilder.Entity("FootballClubEntityFootballLeagueEntity", b =>
                {
                    b.HasOne("Personal.Dashboard.Core.Clubs.Entities.FootballClubEntity", null)
                        .WithMany()
                        .HasForeignKey("ClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", null)
                        .WithMany()
                        .HasForeignKey("LeaguesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Clubs.Entities.FootballClubAlias", b =>
                {
                    b.HasOne("Personal.Dashboard.Core.Clubs.Entities.FootballClubEntity", "Club")
                        .WithMany("Aliases")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueAlias", b =>
                {
                    b.HasOne("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", "League")
                        .WithMany("Aliases")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueSeason", b =>
                {
                    b.HasOne("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Clubs.Entities.FootballClubEntity", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Personal.Dashboard.Core.Leagues.Entities.FootballLeagueEntity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
