<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Aspire.Hosting" />
    <Using Include="Aspire.Hosting.Testing" />
    <Using Include="Microsoft.Playwright" />
    <Using Include="Microsoft.Playwright.Assertions" Static="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.1.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.50.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Personal.Dashboard.Host\Personal.Dashboard.Host.csproj" />
  </ItemGroup>

</Project>
