<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>06ce3e63-45e5-4a9a-a4a2-6d006e3b3091</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Personal.Dashboard.Api.Host\Personal.Dashboard.Api.Host.csproj" />
    <ProjectReference Include="..\Personal.Dashboard.Migrations.Host\Personal.Dashboard.Migrations.Host.csproj" />
    <ProjectReference Include="..\Personal.Dashboard.Web.Host\Personal.Dashboard.Web.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire4Wasm.AppHost" Version="6.0.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.1" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.1" />
  </ItemGroup>

</Project>
