<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Personal.Dashboard.Core\Personal.Dashboard.Core.csproj" />
    <ProjectReference Include="..\Personal.Dashboard.Test.Support\Personal.Dashboard.Test.Support.csproj" />
  </ItemGroup>

</Project>