<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\Personal.Dashboard.Models\Personal.Dashboard.Models.csproj" />
    </ItemGroup>
</Project>
