name: Main Build
on: [push]

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        name: Setup .NET
        with:
          global-json-file: global.json

      - name: Restore Tools
        run: dotnet tool restore

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pull Docker Images
        run: docker pull postgres:18-alpine

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --no-restore --filter "Category!=Feature"

      - name: Install Playwright Browsers
        run: pwsh tests/Personal.Dashboard.Feature.Tests/bin/Release/net10.0/playwright.ps1 install chromium

      - name: Run Feature Tests
        run: dotnet test tests/Personal.Dashboard.Feature.Tests --configuration Release --no-build --no-restore --filter "Category=Feature"