name: Main Build
on: [push]

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        name: Setup .NET
        with:
          global-json-file: global.json

      - name: Restore Tools
        run: dotnet tool restore

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --no-restore